### ISSUE TITLE
The name of the target is not updatated when a fixed horizontal point is commanded (via schedule)

### ISSUE THREAD

**Issue by flyingfrog81** [discos/discos#10]
Originally reported by @aorlati
Date Submitted: 2012-10-02
Category: ticket
OS: 
OS Version: 
Platform: 
Priority: normal
Product Version: NURAGHE-0.1
Project: Nuraghe
Reproducibility: always
Resolution: open
Severity: minor
Status: assigned
Updated: 2016-01-14
[Link to original mantis issue #0000027](http://www.med.ira.inaf.it/mantisbt/view.php?id=0000027)

**Comment by aorlati** [comment]
outdate and probably solved. I'm closing it.
