### ISSUE TITLE
the configuration of xxp receiver sometimes fails

### ISSUE THREAD

**Issue by flyingfrog81** [discos/discos#11]
Originally reported by @aorlati
Date Submitted: 2012-10-02
Category: ticket
OS: 
OS Version: 
Platform: 
Priority: low
Product Version: ESCS-0.2
Project: ESCS
Reproducibility: sometimes
Resolution: open
Severity: minor
Status: assigned
Updated: 2012-10-02
[Link to original mantis issue #0000029](http://www.med.ira.inaf.it/mantisbt/view.php?id=0000029)

**Comment by aorlati** [comment]
Outdated. I'm closing it.
