### ISSUE TITLE
Timeout of data acquisition causes crash of whole system

### ISSUE THREAD

**Issue by flyingfrog81** [discos/discos#14]
Originally reported by @aorlati
Date Submitted: 2012-12-12
Category: ticket
OS: 
OS Version: 
Platform: 
Priority: normal
Product Version: NURAGHE-0.2
Project: Nuraghe
Reproducibility: random
Resolution: open
Severity: crash
Status: new
Updated: 2012-12-12
[Link to original mantis issue #0000051](http://www.med.ira.inaf.it/mantisbt/view.php?id=0000051)

**Comment by aorlati** [comment]
Outdated. I'm closing it.
