### ISSUE TITLE
remote command to collect information from telescope required by pulsar acquisition system

### ISSUE THREAD

**Issue by flyingfrog81** [discos/discos#15]
Originally reported by @aorlati
Date Submitted: 2012-11-23
Category: feature
OS: 
OS Version: 
Platform: 
Priority: low
Product Version: NURAGHE-0.1
Project: Nuraghe
Reproducibility: N/A
Resolution: open
Severity: feature
Status: assigned
Updated: 2016-01-14
[Link to original mantis issue #0000043](http://www.med.ira.inaf.it/mantisbt/view.php?id=0000043)

**Comment by aorlati** [comment]
@carlomigoni, @giuseppe-carboni  do you think we can close this? Is there any other request from Pulsar Software do be fulfilled?

**Comment by giuseppe-carboni** [comment]
We have separate, more detailed issues for any other request, I think it's ok to close this one.
