### ISSUE TITLE
getAttenuations command does not work

### ISSUE THREAD

**Issue by flyingfrog81** [discos/discos#18]
Originally reported by @marco-buttu
Date Submitted: 2013-12-12
Category: ticket
OS: 
OS Version: 
Platform: 
Priority: normal
Product Version: NURAGHE-0.2
Project: Nuraghe
Reproducibility: always
Resolution: open
Severity: minor
Status: assigned
Updated: 2016-01-14
[Link to original mantis issue #0000115](http://www.med.ira.inaf.it/mantisbt/view.php?id=0000115)

**Comment by aorlati** [comment]
I'm closing the issue because outdated
