### ISSUE TITLE
schedule checker unexpected beaviour

### ISSUE THREAD

**Issue by flyingfrog81** [discos/discos#28]
Originally reported by @jjpopski
Date Submitted: 2014-12-03
Category: ticket
OS: 
OS Version: 
Platform: 
Priority: normal
Product Version: NURAGHE-0.4
Project: Nuraghe
Reproducibility: have not tried
Resolution: open
Severity: minor
Status: assigned
Updated: 2015-05-05
[Link to original mantis issue #0000162](http://www.med.ira.inaf.it/mantisbt/view.php?id=0000162)

**Comment by aorlati** [comment]
Outdated, I'm closing it.
