### ISSUE TITLE
Fitswriter: huge time passes after stop recording  before finalising file

### ISSUE THREAD

**Issue by flyingfrog81** [discos/discos#34]
Originally reported by @jjpopski
Date Submitted: 2014-07-16
Category: ticket
OS: 
OS Version: 
Platform: 
Priority: normal
Product Version: NURAGHE-0.3
Project: Nuraghe
Reproducibility: always
Resolution: open
Severity: major
Status: new
Updated: 2014-07-17
[Link to original mantis issue #0000154](http://www.med.ira.inaf.it/mantisbt/view.php?id=0000154)

**Comment by jjpopski** [comment]
@aorlati To be closed?

**Comment by aorlati** [comment]
I'm closing the issue. I am not aware of any other reports on this matter and it has been too long to believe it is still valid
