### ISSUE TITLE
keyword "PROG ID" has to be added to the main header of fits file

### ISSUE THREAD

**Issue by flyingfrog81** [discos/discos#40]
Originally reported by @aorlati
Date Submitted: 2014-02-27
Category: feature
OS: 
OS Version: 
Platform: 
Priority: normal
Product Version: ESCS-0.3
Project: ESCS
Reproducibility: N/A
Resolution: open
Severity: feature
Status: new
Updated: 2014-02-27
[Link to original mantis issue #0000132](http://www.med.ira.inaf.it/mantisbt/view.php?id=0000132)

**Comment by aorlati** [comment]
I'm closing this old issue as it will be addressed  in #348
