### ISSUE TITLE
Mail delivery support API

### ISSUE THREAD

**Issue by aorlati** [discos/discos#556]
A support for sending email to system administrators should be added. 
This has implications also to system deployment ad the mail service should be configured.

This call should be added to Noto and Medicina mount control when a pendolation of the servo system is detected

**Comment by aorlati** [comment]
In order to make this enhancement work a proper configuration of the mail service should be done in the workstation. 
This will involve the deployment system and an issue to be open (@giuseppe-carboni).
Particularly 
1) install agent "postfix"
2) configure it with a proper mail server. The file do be set is "/etc/postfix/main.cf" changind the following keyword accordingly
`myhostname =` 
`relayhost = `

**Comment by giuseppe-carboni** [comment]
Seems like no further configuration is needed when the mail is sent by a machine under a station's domain. Same applies with virtual machines. When the machines is in SRT or Medicina network, the mail gets sent successfully. I cannot send any mail with the `mail` command when working from home.

**Comment by giuseppe-carboni** [comment]
We forgot to add `DiscosLocals` library in the main Makefile
