### ISSUE TITLE
ManagementContainer, "Error in schedule reporting" after haltSchedule/stopSchedule

### ISSUE THREAD

**Issue by giuseppe-carboni** [discos/discos#587]
This warning message should not appear since it was the user to choose to halt/stop the schedule

**Comment by giuseppe-carboni** [comment]
@aorlati I believe the issue is here:
https://github.com/discos/discos/blob/master/Common/Servers/Scheduler/src/ScheduleExecutor.cpp#L793
which calls the following method:
https://github.com/discos/discos/blob/master/Common/Servers/Scheduler/src/ScheduleReport.cpp#L110
which returns false for an error somewhere, or true when no error is found.
I believe the condition in the first if should be inverted by heading the call with a `!`.
Asking your opinion on this since I'm not 100% sure.

**Comment by aorlati** [comment]
Hit the head of the nail! 
You can fix it and issue a PR.
Thanks.
