### ISSUE TITLE
Common Active Surface interface files clash with Noto Active Surface interface files

### ISSUE THREAD

**Issue by giuseppe-carboni** [discos/discos#644]

**Comment by fvitello** [comment]
I am addressing this in fix-issue-613 (https://github.com/discos/discos/commits/fix-issue-613). 

Notes:

 Noto/Interfaces/NotoActiveSurfaceInterface/idl/NotoActiveSurfaceBoss.midl 
- add include of ActiveSurfaceCommon.idl
- Remove enum TASonewayaction and TASprofile

**Comment by giuseppe-carboni** [comment]
@fvitello this seems to be fixed by now, I guess we can close the issue
