### ISSUE TITLE
AsOff and AsOn commands are disabled  the system is not set up.

### ISSUE THREAD

**Issue by aorlati** [discos/discos#745]

**Comment by giuseppe-carboni** [comment]
Can you detail this a little better? I don't understand if asOn and asOff are now disabled without commanding a setup first, and this behavior should be changed to something else, or if they are working right now and they should be disabled without a setup command first.

**Comment by aorlati** [comment]
@carlomigoni, do you have any clue about this issue?

**Comment by carlomigoni** [comment]
The setup of the active surface is made in the same way on the three antennas:
asSetup=S/SF/P/PF for SRT
asSetup=P/PF for Medicina/Noto
the asOn and asOff commands are used internally by asSetup and don't have to be used by user/operator

**Comment by aorlati** [comment]
Not an issue
