### ISSUE TITLE
Script discosdown does not remove the file lock

### ISSUE THREAD

**Issue by marco-buttu** [discos/discos#784]
The current version of ACS changed the behaviour of `killACS`, now it does not remove the file lock. In the script `discosdown` we are calling `killACS`, we should change to `acsStop`.

**Comment by giuseppe-carboni** [comment]
acsStop takes a very long time to shutdown ACS, I'm currently using `killACS`, which kills the processes rather quickly, followed by `acsStop`, which will only take care of removing the file lock. I suggest we follow this strategy.

**Comment by aorlati** [comment]
Can you provide more details? where is the script discosdown? DISCOS or Provisioning? 
The other question: what about the acscommandcenter, did they change acstop e killacs buttons as well?
