### ISSUE TITLE
Wrong check of schedule filename lenght

### ISSUE THREAD

**Issue by marco-buttu** [discos/discos#785]
In [Schedule.cpp](https://github.com/discos/discos/blob/master/Common/Servers/Scheduler/src/Schedule.cpp#L115) there is a check about the maximum lenght of the schedule filename. The check is currently done to the full path, not just the schedule name. In should be changed in order to check just the file name.

**Comment by aorlati** [comment]
I think this check: https://github.com/discos/discos/blob/766b0dd9fbe674271b333b9d8a91c63aeddd2ae1/Common/Servers/Scheduler/src/Schedule.cpp#L115
should be done on m_baseName member variable.

**Comment by giuseppe-carboni** [comment]
We should fix this onto the master branch as well.
