### ISSUE TITLE
Noise Mark table must be added for the K band receiver when the selected mode is VLBI

### ISSUE THREAD

**Issue by flyingfrog81** [discos/discos#8]
Originally reported by @aorlati
Date Submitted: 2012-10-02
Category: feature
OS: 
OS Version: 
Platform: 
Priority: normal
Product Version: NURAGHE-0.1
Project: Nuraghe
Reproducibility: always
Resolution: open
Severity: feature
Status: assigned
Updated: 2016-01-14
[Link to original mantis issue #0000026](http://www.med.ira.inaf.it/mantisbt/view.php?id=0000026)

**Comment by aorlati** [comment]
I think VLBI mode in K-band receiver is sort of deprecated as it has not ever been used. I'm closing this issue with the intention to reopen it if the mode comes out again.
