### ISSUE TITLE
Implementing Clow-band receiver component for the SRT

### ISSUE THREAD

**Issue by aorlati** [discos/discos#806]
Mapping of control boards should be identical to the 7GHz, so we can probably reuse the same code.

**Comment by aorlati** [comment]
Just pushed a commit. Preliminary support. I wait for a more complete implementation before PR into centos7_campatibility_branch.

**Comment by giuseppe-carboni** [comment]
@aorlati, @sergiopoppi can this be closed or we still need to implement something regarding the CLow component?
