### ISSUE TITLE
SRT K band receiver, adjusting control software to the new LNA bias board (GAIA)

### ISSUE THREAD

**Issue by aorlati** [discos/discos#820]
My quick and dirty solution is to comment out all code referring to LNA control via the old board. The software for the new board should be added later.

**Comment by aorlati** [comment]
Looking at the code, we should also get rid of the derotator control.

**Comment by sergiopoppi** [comment]
Problems with connecting the component. 

![image](https://github.com/discos/discos/assets/10814075/c0255b15-2f7b-47c4-a6d4-3ea36a054b72)

**Comment by sergiopoppi** [comment]
Ignore previous comment. The fault was wrong ip of the dewar board.
