### ISSUE TITLE
RFIMonitoring floods the LoggingClient when LO cannot be retrieved

### ISSUE THREAD

**Issue by giuseppe-carboni** [discos/discos#830]
I suggest using LOGFILTER instead of logging the exception every time. This is happening due to the RFI monitoring client sending the antennaParameters command continuously

**Comment by carlomigoni** [comment]
I solved some months ago using the LogDike class but I forgot to upload the modifications. issue 797

**Comment by giuseppe-carboni** [comment]
Duplicated of #797, closing
