### ISSUE TITLE
Possible bug in SRTMount/CommonData.cpp

### ISSUE THREAD

**Issue by giuseppe-carboni** [discos/discos#864]
@aorlati take a look at [this line](https://github.com/discos/discos/blob/master/SRT/Servers/SRTMount/src/CommonData.cpp#L359). Seems like we are setting the elevation axis state using the azimuth value.

**Comment by aorlati** [comment]
Yep. That's a bug. Can you fix it?

**Comment by giuseppe-carboni** [comment]
Sure, I'll take care of it
