### ISSUE TITLE
when performing On The fly scans the log is flooded with warning messages: AZ_RATE_BEYOND_RECCOMENDED_LIMIT"

### ISSUE THREAD

**Issue by flyingfrog81** [discos/discos#9]
Originally reported by @aorlati
Date Submitted: 2012-10-02
Category: ticket
OS: 
OS Version: 
Platform: 
Priority: low
Product Version: ESCS-0.2
Project: ESCS
Reproducibility: sometimes
Resolution: open
Severity: minor
Status: assigned
Updated: 2016-03-24
[Link to original mantis issue #0000023](http://www.med.ira.inaf.it/mantisbt/view.php?id=0000023)

**Comment by aorlati** [comment]
outdated. closing this issue.
